# Generated by Django 4.0.5 on 2022-06-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('designation', models.CharField(choices=[('SE', 'SE'), ('ASE', 'ASE'), ('SE', 'SE')], default='SE', max_length=30)),
                ('work_location', models.CharField(choices=[('BENGALURU', 'BENGALURU'), ('HYDERABAD', 'HYDERABAD')], default='HYDERABAD', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
