# Generated by Django 4.0.5 on 2022-06-13 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_alter_eventphotos_event_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='event_comment',
        ),
        migrations.AddField(
            model_name='events',
            name='event_category',
            field=models.CharField(choices=[('R AND R', 'R AND R'), ('BIRTHDAY', 'BIRTHDAY'), ('ANNIVERSARY', 'ANNIVERSARY')], default='R AND R', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbackid', to='community.events'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_givenby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_reaction', models.CharField(choices=[('INTERESTED', 'INTERESTED'), ('NOT INTERESTED', 'NOT INTERESTED'), ('GOING', 'GOING')], default='PHOTO', max_length=20)),
                ('posted_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_posted', to='community.events')),
                ('reacted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['posted_event', 'event_reaction', 'reacted_user'],
                'abstract': False,
            },
        ),
    ]
