# Generated by Django 4.0.5 on 2022-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_feedback_feedback_event_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreactions',
            name='event_reaction',
            field=models.CharField(choices=[('INTERESTED', 'INTERESTED'), ('NOT INTERESTED', 'NOT INTERESTED'), ('GOING', 'GOING')], default='NOT INTERESTED', max_length=20),
        ),
    ]
