# Generated by Django 4.0.5 on 2022-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_eventreactions_event_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
